### ISSUE TITLE
Chating while sleeping in a bed crashes the game

### ISSUE THREAD

**Issue by janno288** [OldHaven-Network/MegaMod-Mixins#12]
While typing something in chat while sleeping in a bed the game will freeze and completly crash
ava.lang.StringIndexOutOfBoundsException: String index out of range: 35
	at java.lang.String.substring(Unknown Source)
	at gc.a(SourceFile:610)
	at gh.a(SourceFile:47)
	at px.b(SourceFile:553)
	at net.minecraft.client.Minecraft.run(SourceFile:781)
	at java.lang.Thread.run(Unknown Source)
Stopping!

**Comment by ScarletLovell** [comment]
Fixed with https://github.com/OldHaven-Network/MegaMod-Mixins/pull/22

**Comment by ScarletLovell** [comment]
reopening cause it **_apparently_** still exists after being fixed twice.

**Comment by janno288** [comment]
i am now confused what id going on?

**Comment by ScarletLovell** [comment]
Fixed in https://github.com/OldHaven-Network/MegaMod-Mixins/commit/598ddf2378b688581f384aaa9e112ffd6347fd80
