### ISSUE TITLE
Join Server has no effect on the multiplayer screen.

### ISSUE THREAD

**Issue by ghost** [OldHaven-Network/MegaMod-Mixins#16]
Must use direct connect to join any server.

**Comment by ScarletLovell** [comment]
This isn't the case for me, it seems to always work. What server(s) are you trying to add (if it's not private)?

**Comment by ghost** [comment]
I don't know if that's Aether causing this issue but, when adding a server on the list and clicking the "Join Server" button, the game brings me back to the main menu. The server is private for now.

**Comment by ScarletLovell** [comment]
I've actually tested this quite recently with the AetherMP modpack and it seems to work fine for me. What other mods are you using?

**Comment by ghost** [comment]
I am not using the same Aether version as AetherMP, I am using the following mods;
Netherite
Solar Stove
Aether
Mo'Creatures
Dynamic Lights 
Andrewkart's Selective Paints
Andrewkart's Multiplayer Commands
rek's How Many Items
Oldmana's Performance Updates
Oldmana's Modern Chat GUI

**Comment by ScarletLovell** [comment]
is it possible for you to disable your mods one at a time to figure out which one is the issue?

**Comment by ScarletLovell** [comment]
Closing as the issue isn't related to MegaMod
