### ISSUE TITLE
Sign lines array overflow

### ISSUE THREAD

**Issue by mineLdiver** [OldHaven-Network/MegaMod-Mixins#25]
Pressing ENTER on the last line of a sign causes it to try and go to 5th line but ends up crashing the game.

Crashlog: https://ghostbin.co/paste/y54yq

**Comment by ScarletLovell** [comment]
Fixed in https://github.com/OldHaven-Network/MegaMod-Mixins/commit/598ddf2378b688581f384aaa9e112ffd6347fd80
