### ISSUE TITLE
Pressing any key on MultiplayerGUI crashes the game

### ISSUE THREAD

**Issue by janno288** [OldHaven-Network/MegaMod-Mixins#3]
When you press ENTER on the SELECT SERVER MENU
The game cmpletly crashes
and you need to KILL it in MULTIMC

**Comment by ScarletLovell** [comment]
Fixed on https://github.com/OldHaven-Network/MegaMod-Mixins/commit/e003269a03e42b3f186b3210b90014a31f233a0e
