### ISSUE TITLE
Some mod settings do not save after restarting the game

### ISSUE THREAD

**Issue by D3JF** [OldHaven-Network/MegaMod-Mixins#32]
This seems to be occuring to the "Enable Fancy Trees" setting. I wasn't able to check other settings, but they may possibly be affected as well.

**Comment by ScarletLovell** [comment]
Fixed in https://github.com/OldHaven-Network/MegaMod-Mixins/commit/4d689d56a505d4459f905a6a8ea8581acf499f56
