### ISSUE TITLE
All players have the Alex playermodel

### ISSUE THREAD

**Issue by D3JF** [OldHaven-Network/MegaMod-Mixins#37]
I've heard that MegaMod does checks to see if a player model has an Alex skin or not, yet every single player I've encountered so far has an Alex playermodel without exceptions. I thought this would eventually be fixed, but it still seems to be an issue in the latest MegaMod release (0.6.1).

**Comment by ScarletLovell** [comment]
Yeah I've also been reported this issue a few times already. Will try and fix for 0.6.2

**Comment by ScarletLovell** [comment]
fixed in https://github.com/OldHaven-Network/MegaMod-Mixins/commit/acd12d5b39e6672888cede379e245470bb52da4c
