### ISSUE TITLE
Default F5 camera distance places camera inside of player's head

### ISSUE THREAD

**Issue by D3JF** [OldHaven-Network/MegaMod-Mixins#40]
The default F5 camera distance is "30", which places the camera inside of the player's head. It can be manually set to "FAR" in GUI settings, but players may not be aware of this option and will perceive this as a bug.

![2020-05-10_00 40 56](https://user-images.githubusercontent.com/62910865/81486742-6ea69b80-9246-11ea-8f3a-3ee09afdbc13.png)

**Comment by ScarletLovell** [comment]
Fixed in 0.7.0
