### ISSUE TITLE
Vanilla clients crash when a MegaMod client starts typing on a server

### ISSUE THREAD

**Issue by D3JF** [OldHaven-Network/MegaMod-Mixins#47]
![obrazek](https://user-images.githubusercontent.com/62910865/103490139-bac7d100-4e11-11eb-98fa-0ec12ce7507c.png)
This is the message a vanilla client gets kicked with if a MegaMod client tries to type in chat on a server.

**Comment by ScarletLovell** [comment]
Bug has been fixed and appropriate servers have been updated with new packets.
