### ISSUE TITLE
Remove old MinecraftCapes endpoint

### ISSUE THREAD

**Issue by james090500** [OldHaven-Network/MegaMod-Mixins#49]
This endpoint is dead and no longer used

https://github.com/OldHaven-Network/MegaMod-Mixins/blob/3361dcc3613a780445272e5f61772c482bfc8cde/src/main/java/net/oldhaven/customs/util/SkinFix.java#L93

**Comment by james090500** [comment]
Also please use the new up to date base64 endpoints for capes, your current endpoint ignore our caching system and will cause issues for the end users 

https://minecraftcapes.net/profile/ba4161c03a42496c8ae07d13372f3371

**Comment by ScarletLovell** [comment]
Oops, I'm not sure why that `capesList` array is still there, underneeth it is the actual URL.
https://github.com/OldHaven-Network/MegaMod-Mixins/blob/3361dcc3613a780445272e5f61772c482bfc8cde/src/main/java/net/oldhaven/customs/util/SkinFix.java#L111
However, thank you for your issue. I have realized the problem and updating to the newest base64 endpoint.
Ears use a similar system, so it shouldn't be too difficult to convert mccapes to it.

**Comment by james090500** [comment]
Thanks, just a note is that animated capes are a feature so you may want to do some check on the received texture. Something like, if animatedCapes is true then you'll need to crop the image...

**Comment by ScarletLovell** [comment]
Fixed in https://github.com/OldHaven-Network/MegaMod-Mixins/commit/74df9639af789cac29afd77d36fbeeaeae7d1a37
