### ISSUE TITLE
Sleeping crashes the game

### ISSUE THREAD

**Issue by pixelunderscore** [OldHaven-Network/MegaMod-Mixins#5]
Sleeping in a bed will crash the game sometimes.

Error:
java.lang.StringIndexOutOfBoundsException: String index out of range: 18
	at java.lang.String.substring(Unknown Source)
	at gc.a(SourceFile:605)
	at gh.a(SourceFile:47)
	at px.b(SourceFile:553)
	at net.minecraft.client.Minecraft.run(SourceFile:781)
	at java.lang.Thread.run(Unknown Source)
Stopping!

**Comment by ScarletLovell** [comment]
Could be fixed on https://github.com/OldHaven-Network/MegaMod-Mixins/commit/e003269a03e42b3f186b3210b90014a31f233a0e . Have to do more testing to figure this out correctly.

**Comment by ScarletLovell** [comment]
Seems to be fixed with https://github.com/OldHaven-Network/MegaMod-Mixins/commit/e003269a03e42b3f186b3210b90014a31f233a0e
